### PR TITLE
addressing #41

### LINKED ISSUE #41: Taking care of the "SCD "x-schema::tns" didnt match any schema component" error
Hi,

I faced the error "SCD "x-schema::tns" didnt match any schema component" that happens when an episode declares namespaces not used in the xsd of the project using that episode.

This is very annoying and I found out that it is an old bug never fixed: http://metro.1045641.n5.nabble.com/Re-JAXB-2-1-unused-namespaces-in-episode-file-raise-an-exception-td1054910.html

In this thread, they propose as a workaround to add an extra attribute in the generated episode file to the scd elements in order to have them getting ignored later.

Do you think there could be anyway that such a workaround is enforced by maven-jaxb2-plugin? With some kind of post-processing of the generated episode file for example.

Thank you

### PR DESCRIPTION
**Pull request by andreptb**
@highsource,

I've implemented @victornoel XSLT approach, configurable with **allowUnusedSchemaBindingsInEpisodes** property. This worked for me, hopefully will help you resolve #41.

### CODE REVIEW

**Comment by highsource** [comment]
Impressive, thank you.

**Comment by andreptb** [comment]
You're welcome.

**Comment by victornoel** [comment]
Hi, that's great!

Maybe we should name differently the option.
To me, allowUnusedSchemaBindingsInEpisodes would be to accept episode files from dependencies even if they contain unused schema bindings (i.e. the second part of the solution discussed in issue #41).

But the first part, which is generating episode files with the if-exists attributes, is not about allowing anything. I don't know how to name it…

**Comment by andreptb** [comment]
Got it. How about **allowImporWithUnusedSchemaBindingsInEpisode**?

**Comment by victornoel** [comment]
Or we name it after the hack and not the objective, something like: applyEpisodeHackForUnusedSchemaBindings.

Also, do you think it would be hard to implement the complementary solution as part of this pull request? The idea would be to have the xsl applied to episodes while they are read, I think @highsource said in #41 that there was a way to introduce a resource resolver to do so.
For these maybe the configuration should be per episode (when there is many) and the properties would then be allowUnusedSchemaBindingsInEpisodes.

**Comment by highsource** [comment]
I think we'll really have to rework this with resolvers.

**Comment by andreptb** [comment]
@victornoel,

Renamed the property as you suggested. @highsource, when you mention "rework this with resolvers" you mean adding XSLT transformation somewhere in [MavenCatalogResolver](plugin-core/src/main/java/org/jvnet/jaxb2/maven2/resolver/tools/MavenCatalogResolver.java)?

**Comment by highsource** [comment]
Yep. The proposed solution transforms the generated episode file. Which is OK and good but does not help with existing episodes.
I think there's an option to implement something like an entity resolver for episodes which would transform them on acces in the runtime.

As for the episode generation I'd really think about fixing the XJC's episode plugin.
I'll have to think about it.

**Comment by victornoel** [comment]
Ok, so maybe as a first step, it would be better to fix reading of episodes (instead of generation) by using an entity resolver. As for the generation, it is actually not so important if we have the reading that works.

**Comment by andreptb** [comment]
About **fix reading of episodes**, I couldn't find anything about episode's entity resolvers, nor I could think of a way to apply the XSLT transformation right before the episode file is parsed. @highsource , If you have a clear idea of how that could be acchieved maybe I can help.

I agree about fixing XJC's episode plugin to properly resolve the episode generation, this would definitely work for me, since in my case I'm not worried about existing episodes. As for now, I'll be using the *hacked* version of XSLT approach on generation until we find a proper solution.

**Comment by highsource** [comment]
I've thought about it, here's what I think.

The correct place to apply this fix would be the episode plugin in XJC:

https://github.com/gf-metro/jaxb/blob/69471fb27af6a9e990ef2a7873aab64a18e87640/jaxb-ri/xjc/src/main/java/com/sun/tools/xjc/addon/episode/PluginImpl.java

I'd add a "-episode-bindings-if-exists" option and consider it during the generation. This is where this fix *actually* belongs. @andreptb could you please consider sending a fix to the JAXB people as PR?

The problem is, however, that JAXB people don't really seem to be active in applying PRs. So not sure if they'd really do this.

Therefore I think having this workaround in `maven-jaxb2-plugin` is actually OK. I'd name the config element `addEpisodeBindingsIfExists`, nothing with "hacks" etc.

The implementation is OK. My suggestions would be:

* Rename the config element to `addEpisodeBindingsIfExists`, and use true by default (which is reasonable default).
* Rename the method from `setup...` to `transformEpisodeBindings`.
* Don't use a temp file but rather generate a DOMResult in-memory and then serialize it back onto the same episode file.
* I'd move the XSLT to the appropriate package (`org/jvnet/jaxb2/maven2`) so that it's in the same dir structure where the calling class is.
* We'll also need some docs on that: 
  * https://github.com/highsource/maven-jaxb2-plugin/wiki/Using-Episodes
  * https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuration-Cheat-Sheet
* Would be also good to have a test project. I'd suggest taking: https://github.com/highsource/maven-jaxb2-plugin/tree/master/tests/episodes/a, b, c and configure there once with `addEpisodeBindingsIfExists` with none/true/false and add a simple test case to check if the episode file is generated correctly.

@andreptb Would this be something you could overtake?

Now, about applying XSLT on read. This is a nice option, but seems quite complicated to me at the moment. I think, we'll solve, like the 80% case with just generating `if-exists`, so I'd leave it there first. If there will be a need, we'll address this in a new issue.

Thank you guys for your contributions!

**Pull request merged**
