### PR TITLE
Fix "incompatible types: `List<DependencyResource>` cannot be converted to `java.util.List<Dependency>`" error

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
I integrated maven-jaxb2-plugin into Debian recently and had to add these two patches for it. Hope they are useful.

**Comment by highsource** [comment]
`Arrays.<Dependency>` is OK, can be merged.

**Comment by jspricke** [comment]
The internal version gave: "package com.sun.org.apache.xml.internal.resolver does not exist". Should we add org.apache.xml to the classpath, or what would you suggest? We can also leave this as a Debian only patch, if you would be ok with that.

**Comment by highsource** [comment]
> The internal version gave: "package com.sun.org.apache.xml.internal.resolver does not exist".

This is weird. `mvn dependency:tree` on `maven-jaxb2-plugin-core` gives:

```
org.jvnet.jaxb2.maven2:maven-jaxb2-plugin-core:jar:0.14.1-SNAPSHOT
+- javax.xml.bind:jaxb-api:jar:2.3.0:provided
+- org.slf4j:slf4j-api:jar:1.7.25:compile
+- org.apache.commons:commons-lang3:jar:3.2.1:compile
+- com.sun.org.apache.xml.internal:resolver:jar:20050927:compile
+- org.glassfish.jaxb:txw2:jar:2.3.0:compile
+- org.apache.maven:maven-plugin-api:jar:2.0.9:compile
+- org.sonatype.plexus:plexus-build-api:jar:0.0.7:compile
+- org.codehaus.plexus:plexus-utils:jar:1.5.15:compile
+- org.apache.maven:maven-project:jar:2.0.9:compile
|  +- org.apache.maven:maven-settings:jar:2.0.9:compile
|  +- org.apache.maven:maven-profile:jar:2.0.9:compile
|  +- org.apache.maven:maven-model:jar:2.0.9:compile
|  +- org.apache.maven:maven-artifact-manager:jar:2.0.9:compile
|  |  +- org.apache.maven:maven-repository-metadata:jar:2.0.9:compile
|  |  \- org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-2:compile
|  +- org.apache.maven:maven-plugin-registry:jar:2.0.9:compile
|  +- org.apache.maven:maven-artifact:jar:2.0.9:compile
|  \- org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
|     \- classworlds:classworlds:jar:1.1-alpha-2:compile
+- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.5:compile
+- org.apache.maven.plugin-testing:maven-plugin-testing-harness:jar:2.1:test
|  \- org.codehaus.plexus:plexus-archiver:jar:2.2:test
|     \- org.codehaus.plexus:plexus-io:jar:2.0.4:test
\- junit:junit:jar:4.8.1:test
```

The artifact `com.sun.org.apache.xml.internal:resolver:jar:20050927` contains the `com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver` class.

> Should we add org.apache.xml to the classpath, or what would you suggest? We can also leave this as a Debian only patch, if you would be ok with that.

I would like to understand, what's happening first of all.

**Comment by jspricke** [comment]
`com.sun.org.apache.xml.internal:resolver:jar:20050927:compile` is not packaged in Debian (afaik), which is a requirement.

**Comment by highsource** [comment]
`com.sun.org.apache.xml.internal:resolver` is effectively a dependency of `jaxb-xjc`. I don't think we can just throw out this dependency and hope for good...

Another question: why is there a need in a special packaging for Debian? I don't know this story.

**Comment by jspricke** [comment]
Well, I don't trow it out but replace it with the apache version, which should be the same (apart from the package name).

Debian requires to be self contained, i.e. all sources need to be in Debian as well.

**Comment by jspricke** [comment]
I've pushed a patch to add the apache version to the classpath to make this working.

**Comment by jspricke** [comment]
com.sun.tools.xjc.CatalogUtil is using the apache version as well in Debian, if I'm not wrong:
https://salsa.debian.org/java-team/jaxb/blob/master/debian/patches/04-xml-resolver-compatibility.patch

**Comment by jspricke** [comment]
So I would propose to keep that patch in Debian and update this PR to only contain the Arrays fix, would you agree?

**Comment by highsource** [comment]
I think we should keep that patch in Debian. Accepting it into the master will most definitely break things here.

As for the `Arrays` fix, I don't quite understand, what the problem is. `Arrays.asList` is generic so the type parameter for the resulting list should be happily derived. I don't see any warning there - am I missing something?

**Comment by jspricke** [comment]
I updated the PR to only contain the `Arrays` patch. The error I get is:
``
maven-jaxb2-plugin/plugin-core/src/main/java/org/jvnet/jaxb2/maven2/AbstractXJC2Mojo.java:[1303,70] incompatible types: java.util.List<org.jvnet.jaxb2.maven2.DependencyResource> cannot be converted to java.util.List<org.apache.maven.model.Dependency>
``

**Comment by highsource** [comment]
I'm not getting this error, but OK, it's a minor change.

**Pull request merged**
